=== opkop/web/New folder/xml/2dtd-xml/products.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (name, price, description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST product stock CDATA #REQUIRED>
<!ATTLIST product category (ELECTRONICS | COSMETICS) "ELECTRONICS">

=== opkop/web/New folder/xml/2dtd-xml/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "products.dtd">
<products>
    <product stock="20" category="ELECTRONICS">
        <name>Product Name 1</name>
        <price>19.99</price>
        <description>A brief description of the product.</description>
    </product>
    <product stock="30" category="COSMETICS">
        <name>Product Name 2</name>
        <price>19.99</price>
        <description>A brief description of the product.</description>
    </product>
</products>
